import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { site } from "../src/content/site.mjs";
import { renderAboutPage } from "../src/pages/about.mjs";
import { renderArticlePage } from "../src/pages/article.mjs";
import { renderHomePage } from "../src/pages/home.mjs";
import { renderProjectPage } from "../src/pages/project.mjs";
import { renderProjectPrivacyPage } from "../src/pages/project-privacy.mjs";
import { renderWorkIndexPage } from "../src/pages/work-index.mjs";
import { renderWritingIndexPage } from "../src/pages/writing-index.mjs";
import { loadArticles, loadProjectPrivacy, loadProjects, validateContentRelationships } from "../src/lib/content.mjs";
import { escapeXml } from "../src/lib/html.mjs";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDirectory, "..");
const outputRoot = resolve(projectRoot, "_site");
const generatedNotice = "<!-- Generated by npm run build. Edit files in src/, styles/, and js/. -->\n";
const generatedCssNotice = "/* Generated by npm run build. Edit files in styles/. */\n";
const styleFiles = ["tokens.css", "base.css", "layout.css", "components.css", "article.css", "motion.css"];

async function writeOutput(relativePath, contents) {
  const outputPath = resolve(outputRoot, relativePath);
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, contents, "utf8");
  console.log(`Built ${relativePath}`);
}

function renderFeed(articles) {
  const items = articles.map((article) => `<item>
    <title>${escapeXml(article.title)}</title>
    <link>${site.url}${article.href}</link>
    <guid>${site.url}${article.href}</guid>
    <pubDate>${new Date(`${article.published}T12:00:00Z`).toUTCString()}</pubDate>
    <description>${escapeXml(article.summary)}</description>
  </item>`).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"><channel>
  <title>${escapeXml(site.name)} writing</title>
  <link>${site.url}/writing/</link>
  <description>${escapeXml(site.description)}</description>
  ${items}
</channel></rss>`;
}

function renderSitemap(projects, articles, extraPaths = []) {
  const paths = ["/", "/about/", "/work/", "/writing/", ...projects.map((project) => `/work/${project.id}/`), ...articles.map((article) => article.href), ...extraPaths];
  const entries = paths.map((path) => `<url><loc>${site.url}${path}</loc></url>`).join("");
  return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${entries}</urlset>`;
}

function renderLegacyAboutRedirect() {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=/about/"><link rel="canonical" href="${site.url}/about/"><title>About Yan Liang</title></head><body><a href="/about/">Continue to About</a></body></html>`;
}

await rm(outputRoot, { recursive: true, force: true });
await mkdir(outputRoot, { recursive: true });

const includeDrafts = process.argv.includes("--drafts");
const [allArticles, allProjects, tinyExhibitPrivacy] = await Promise.all([
  loadArticles({ includeDrafts: true }),
  loadProjects({ includeDrafts: true }),
  loadProjectPrivacy("the-tiny-exhibit"),
]);
validateContentRelationships(allProjects, allArticles);

const publishedArticles = allArticles.filter((article) => !article.draft);
const publishedProjects = allProjects.filter((project) => !project.draft);
const articles = includeDrafts ? allArticles : publishedArticles;
const projects = (includeDrafts ? allProjects : publishedProjects)
  .map((project, index) => ({ ...project, number: String(index + 1).padStart(2, "0") }));

const pages = [
  ["index.html", renderHomePage({ articles, projects })],
  ["about/index.html", renderAboutPage()],
  ["about.html", renderLegacyAboutRedirect()],
  ["work/index.html", renderWorkIndexPage({ projects })],
  ["writing/index.html", renderWritingIndexPage({ articles })],
  ...projects.map((project) => [`work/${project.id}/index.html`, renderProjectPage({ project, articles })]),
  [tinyExhibitPrivacy.outputPath, renderProjectPrivacyPage({ privacy: tinyExhibitPrivacy })],
  ...articles.map((article) => [article.outputPath, renderArticlePage({ article, articles, projects })]),
];

for (const [relativePath, markup] of pages) {
  await writeOutput(relativePath, generatedNotice + markup);
}

const styles = await Promise.all(styleFiles.map((filename) => readFile(resolve(projectRoot, "styles", filename), "utf8")));
await writeOutput("styles.css", `${generatedCssNotice}${styles.join("\n")}`);
await cp(resolve(projectRoot, "js/main.js"), resolve(outputRoot, "script.js"));
await cp(resolve(projectRoot, "assets"), resolve(outputRoot, "assets"), { recursive: true });

const fontFiles = [
  ["@fontsource-variable/newsreader/files/newsreader-latin-wght-normal.woff2", "newsreader-latin.woff2"],
  ["@fontsource-variable/newsreader/files/newsreader-latin-wght-italic.woff2", "newsreader-latin-italic.woff2"],
  ["@fontsource-variable/instrument-sans/files/instrument-sans-latin-wght-normal.woff2", "instrument-sans-latin.woff2"],
];
await mkdir(resolve(outputRoot, "assets/fonts"), { recursive: true });
for (const [source, filename] of fontFiles) {
  await cp(resolve(projectRoot, "node_modules", source), resolve(outputRoot, "assets/fonts", filename));
}

await writeOutput("feed.xml", renderFeed(publishedArticles));
await writeOutput("sitemap.xml", renderSitemap(publishedProjects, publishedArticles, [tinyExhibitPrivacy.href]));
await writeOutput("robots.txt", `User-agent: *\nAllow: /\nSitemap: ${site.url}/sitemap.xml\n`);
