import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { renderPage } from "../src/page.mjs";
import { renderAboutPage } from "../src/about.mjs";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDirectory, "..");
const generatedNotice = "<!-- Generated by npm run build. Edit files in src/. -->\n";
const pages = [
  ["index.html", renderPage()],
  ["about.html", renderAboutPage()],
];

for (const [filename, markup] of pages) {
  const outputPath = resolve(projectRoot, filename);
  await writeFile(outputPath, generatedNotice + markup, "utf8");
  console.log(`Built ${outputPath}`);
}
