import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { renderPage } from "../src/page.mjs";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDirectory, "..");
const outputPath = resolve(projectRoot, "index.html");
const generatedNotice = "<!-- Generated by npm run build. Edit files in src/. -->\n";

await writeFile(outputPath, generatedNotice + renderPage(), "utf8");
console.log(`Built ${outputPath}`);
